using System;
using System.Collections.Generic;
using System.Text;

namespace CsharpFeatures
{

    public struct Trainee
    {
        public int Id;
        public string Name;
        public string Technology;
    }
    internal class Basics
    {
        //enum is a value type that defines a set of named
        //constants. It is used to represent a group of related
        //values in a more readable and maintainable way. Enums can be used to improve code clarity and reduce the likelihood of errors by providing meaningful names for constant values. In C#, enums are defined using the "enum" keyword, followed by the name of the enum and a list of named constants enclosed in curly braces. By default, the underlying type of an enum is int, and the constants are assigned sequential integer values starting from 0, but you can specify a different underlying type and assign custom values if needed.
        public enum RGB { Red=100, Green, Blue };
        static void Main(string[] args)
        {
            string myName;
            myName= Console.ReadLine();
            Console.WriteLine("Hello "+myName);

            // CLR - Common Language Runtime
            // execution engine for .net
            // 1. Memory management: CLR handles memory allocation and deallocation for .NET applications, including garbage collection, which automatically frees up memory that is no longer in use.
            //it just manages the memory of managed code only,
            //it does not manage the memory of unmanaged code
            //(e.g., code written in C++ that interacts with .NET
            //applications through interop
            //SQLConnection object, Printer object, File Handles objects's
            // memory management will not be handled by CLR, it will be handled by the unmanaged
            // code that creates and manages those objects.
            // The CLR is responsible for managing the memory of managed code,
            // which is code that is written in .NET languages and runs within the .NET runtime environment.
            // Unmanaged code, on the other hand, is code that is not managed by the .NET runtime
            // and is typically written in languages like C or C++. The memory management of unmanaged code
            // is the responsibility of the developer, and it may involve manual allocation and deallocation of memory using functions like malloc and free in C or new and delete in C++. Therefore, when working with unmanaged resources in .NET applications, developers need to ensure that they properly manage memory to avoid issues such as memory leaks or dangling pointers, as the CLR will not handle this for them.
            //will not be ).
            //Unmanaged code is responsible for its own memory management,
            //and developers need to ensure that they properly allocate
            //and deallocate memory when working with unmanaged resources
            //in .NET applications.
            // 2. Execution of code: CLR compiles the intermediate language (IL) code generated by .NET languages into native machine code that can be executed by the operating system. This allows for platform independence, as the same IL code can run on different platforms with the appropriate CLR implementation.

            // 3. Security: CLR provides a security model that allows developers to specify permissions for code execution, helping to protect against unauthorized access and malicious code.
            // 4. Exception handling: CLR provides a structured exception handling mechanism that allows developers to catch and handle exceptions in a consistent way across different .NET languages.
            // 5. Convert code to IL code and then to machine code, and it also provides a runtime environment for executing .NET applications, including features like memory management, security, and exception handling. The CLR is a key component of the .NET framework that enables cross-language interoperability and provides a consistent execution environment for .NET applications.

            // 2 stage compilation happens in .NET framework
            // 1. Source code is compiled to IL code by the language compiler.
            // 2. IL code is then compiled to native machine code by the JIT (Just-In-Time) compiler at runtime.

            // CTS - Common Type System
            // .Net framework supports different programming languages and the CTS defines how types are declared, used, and managed in the .NET environment. It ensures that objects written in different languages can interact with each other, as long as they adhere to the CTS rules. The CTS provides a common set of data types and rules for type compatibility, which allows for seamless integration between languages and promotes code reuse across different platforms. It also enables features like garbage collection, exception handling, and interoperability between managed and unmanaged code. Overall, the CTS is a fundamental component of the .NET framework that
            // resolves the data types across languages in .NET and
            // provides a framework for cross-language integration, type safety, and high performance code execution.

            // in C# int
            // in VB.NET Integer

            // internally both are represented as System.Int32 in the .NET framework, which is a 32-bit signed integer type defined in the Common Type System (CTS). This means that regardless of the programming language used, when you declare an integer variable, it will be treated as a System.Int32 type in the .NET environment. This allows for seamless interoperability between different languages and ensures that data types are
            // consistent across the .NET framework.

            int myScore;
            myScore =Convert.ToInt32(Console.ReadLine());

            float mySalary;
            mySalary = Convert.ToSingle(Console.ReadLine());

            int a = 10;
            float b = a; // implicit conversion from int to float

            float c= 3.14f;
            int d =(int) c; // explicit conversion from float to int, this will truncate the decimal part and assign the value 3 to d

            // value types and reference types
            // Value types hold their data directly,
            // while reference types store a reference(address) to the
            // actual data.
            // In C#, all primitive types (int, float, bool, etc.)
            // are value types, while complex types
            // (classes, arrays, etc.) are reference types.

            int x = 5; // value type
            int y = x; // y is a copy of x
            y = y + 20; // changing y does not affect x
            Console.WriteLine($"x: {x}, y: {y}");

            string str1 = "Hello"; // reference type
            string str2 = str1; // str2 references the same string as str1
            str2 = str2 + " World"; // changing str2 creates a new string, str1 remains unchanged
            Console.WriteLine($"str1: {str1}, str2: {str2}");


            // Boxing and Unboxing
            // object is the base class for all types in C#, including value types. When a value type is assigned to an object variable, it is "boxed" - meaning that the value is wrapped in an object and stored on the heap. When the value is retrieved from the object variable, it is "unboxed" - meaning that the value is extracted from the object and stored back on the stack.

            int num = 42; // value type
            object obj = num; // boxing: num is boxed into an object
            int unboxedNum = (int)obj; // unboxing: obj is unboxed back into an int

            string place = null;
            //int salary = null; this will give a compile-time error because value types cannot be null unless they are nullable types (e.g., int? salary = null;). Reference types, like string, can be null, which indicates that they do not reference any object in memory.
            //Nullable<int> salary= null; // using Nullable<T> to allow a value type to be null
            int? salary = null; // easy way to declare a nullable value type using the shorthand syntax. This allows the salary variable to hold either an integer value or null, providing flexibility in scenarios where a value may not be applicable or available.

            if (salary.HasValue)
            {
                Console.WriteLine($"Salary: {salary.Value}");
            }
            else
            {
                Console.WriteLine("Salary is not available.");
            }

            // Null Coalescing Operator (??)
            string myplace = null;
            string location = myplace ?? "Unknown"; // if place is null, use "Unknown"
            Console.WriteLine($"Location: {location}");

            int? nullablenumber = null;
            int result = nullablenumber ?? 100; // if nullablenumber is null, use 100

            Console.WriteLine($"The first color is {RGB.Red}");
            Console.WriteLine($"The value of the first color is {(int)RGB.Red}");

            string[] colors = Enum.GetNames(typeof(RGB));
            Console.WriteLine("Available colors:");
            foreach (string color in colors)
            {
                Console.WriteLine(color);
            }

            int[] colorvalues=(int[]) Enum.GetValues(typeof(RGB));
            Console.WriteLine("Color values:");
            foreach (int value in colorvalues)
            {
                Console.WriteLine(value);
            }

            Trainee trainee= new Trainee();
            trainee.Id = 1;
            trainee.Name = "John Doe";
            trainee.Technology = "CSharp";

            Console.WriteLine($"Trainee ID: {trainee.Id}");
            Console.WriteLine($"Trainee Name: {trainee.Name}");
            Console.WriteLine($"Trainee Technology: {trainee.Technology}");

        }
    }
}
